#/bash/bin

#Isolates and orders Symbols(column 7) and P-Adj(column 3) from results table 
#Results table is generated by DESeq2 and "ashr"
echo DISCLAIMER: Results table MUST have symbols column and use lfcShrink \(..., type = \"ashr\"\)

#Creates base name "_example"
name=$(basename "$1" |  sed 's/\.csv\|res//g')

#Isolates symbols and padj columns and sorts
#-r = reverse
#-g = include numeric scientic notation
#-k2 = sort by column 2

# output column for GSEA ranking is column 3, log2FoldChange
awk -F, '{if($7 != "NA" && NR != 1){print $7 "\t" $3 }}' $1  | sort -rgk2  >> gsea${name}.rnk 

#Comments in header
sed -i '1 i\#symbol	log2FoldChange' gsea${name}.rnk
#Removes "" from symbols
sed -i 's/"//g' gsea${name}.rnk

